# 创建表
CREATE TABLE DATA_VECTOR (
        ID  INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
        FILENAME CHAR(64),
        FILEPATH CHAR(255),
        VGG16FEAT BLOB,
        LBPFEAT BLOB,
        COLORFEAT BLOB,
        GLCMFEAT BLOB,
        VITFEAT BLOB,
        INDEX(ID))

# 检索所有数据
SELECT * FROM DATA_VECTOR ORDER BY ID

# 根据id检索数据
SELECT * FROM DATA_VECTOR WHERE ID = %s

# 插入示例数据
INSERT INTO DATA_VECTOR(FILENAME, FILEPATH, 
        VGG16FEAT, LBPFEAT, COLORFEAT, GLCMFEAT, VITFEAT)
        VALUES ("1.jpg", "/home/test/1.jpg", " ", " ", " ", " ", " ")

# 插入数据
INSERT INTO DATA_VECTOR(FILENAME, FILEPATH, VGG16FEAT, LBPFEAT, COLORFEAT, GLCMFEAT, VITFEAT) \
        VALUES (%s, %s, _binary %s, _binary %s, _binary %s, _binary %s, _binary %s)

# 重置表id
ALTER TABLE DATA_VECTOR DROP ID;
ALTER TABLE DATA_VECTOR ADD ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;
